version: "3"

services:
  golang:
    build: ./app
    tty: true
    volumes:
      - .:/go/src/work
    ports:
      - "3000:3000"
    # command: bash -c "cd app && realize start --server"
  nginx:
    build: ./nginx
    ports:
      - "8090:8090"
    depends_on:
      - "golang"
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./Certs/:/var/lib/https-portal/
    environment:
      DOMAINS: 'golang.local -> http://nginx:8090'
      STAGE: "local"
      # FORCE_RENEW: 'true'